### ISSUE TITLE
能不能增加修改ttl的功能

### ISSUE THREAD

**Issue by yeezylife** [c2xvi/easier-mosdns#1]
很感谢你的这个项目让我终于用上了4.x版本。

我自己加了一个修改ttl的插件:

```
  - tag: "modify_ttl"
    type: "ttl"
    args:
      minimal_ttl: 1200
      maximum_ttl: 86400
```

然后用另一个sequence插件把他们串起来了：

```
  - tag: sequence
    type: sequence
    args:
      exec:
        - cache
        - main_sequence # 运行主执行序列
        - modify_ttl # 修改 ttl
```

但我在想有必要用两次sequence插件么，我想直接在server后面写：

```
servers:
  - exec:
      - cache
      - main_sequence # 运行主执行序列
      - modify_ttl # 修改 ttl
```

但我是笨笨，总觉得自己把缩进搞错了

**Comment by c2xvi** [comment]
感谢你的提议，实际上这个config最早有 `modify_ttl` ，是我自行删除的😂。

实际上配置好 `modify_ttl` 之后可以直接在 `main_sequence` 下加入，如下：
```
- tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - cache

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return
 
         # 修改ttl
         - modify_ttl
......
```

具体可参见 https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns/cha-jian-ji-qi-can-shu#ttl-xiu-gai-ying-da-de-sheng-cun-shi-jian
